# Generated by Django 6.0.1 on 2026-01-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0032_familyconfiguration_bank_reconciliation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Enable email notifications'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_notify_new_transaction',
            field=models.BooleanField(default=False, help_text='Receive email for new transactions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_notify_overbudget',
            field=models.BooleanField(default=False, help_text='Receive email for over budget alerts'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_notify_overdue',
            field=models.BooleanField(default=False, help_text='Receive email for overdue transactions'),
        ),
    ]
