# Generated by Django 6.0.1 on 2026-02-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0033_customuser_email_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='last_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
