# Generated by Django 6.0.1 on 2026-02-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0034_notification_last_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='email_notify_overdue_days_before',
            field=models.IntegerField(default=0, help_text='Send overdue warning X days before due date (0 = only when already overdue)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_opted_out',
            field=models.BooleanField(default=False, help_text="User clicked 'stop receiving emails' for this notification"),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_opted_out_at',
            field=models.DateTimeField(blank=True, help_text='When user opted out of emails for this notification', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='unsubscribe_token',
            field=models.CharField(blank=True, help_text='Token for email unsubscribe link', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('OVERDUE', 'Overdue Transaction'), ('OVERDUE_WARNING', 'Upcoming Due Date'), ('OVERBUDGET', 'Over Budget'), ('NEW_TRANSACTION', 'New Transaction')], max_length=20),
        ),
    ]
