# Generated by Django 6.0.3 on 2026-03-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0035_familymember_email_notify_overdue_days_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's preferred timezone for displaying dates", max_length=50),
        ),
    ]
